/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\知识库\\blogs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3851a994",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3851a994").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0384a2da",
    path: "/blogs/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0384a2da").then(next)
    },
  },
  {
    name: "v-499d3784",
    path: "/handle/%E6%89%8B%E5%86%99Promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-499d3784").then(next)
    },
  },
  {
    path: "/handle/手写Promise.html",
    redirect: "/handle/%E6%89%8B%E5%86%99Promise.html"
  },
  {
    path: "/handle/手写Promise.html",
    redirect: "/handle/%E6%89%8B%E5%86%99Promise.html"
  },
  {
    name: "v-540052e4",
    path: "/blogs/this%E5%85%B3%E9%94%AE%E5%AD%97%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-540052e4").then(next)
    },
  },
  {
    path: "/blogs/this关键字总结.html",
    redirect: "/blogs/this%E5%85%B3%E9%94%AE%E5%AD%97%E6%80%BB%E7%BB%93.html"
  },
  {
    path: "/blogs/this关键字总结.html",
    redirect: "/blogs/this%E5%85%B3%E9%94%AE%E5%AD%97%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-395e7a4c",
    path: "/blogs/git%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-395e7a4c").then(next)
    },
  },
  {
    path: "/blogs/git常用指令.html",
    redirect: "/blogs/git%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html"
  },
  {
    path: "/blogs/git常用指令.html",
    redirect: "/blogs/git%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html"
  },
  {
    name: "v-3c9a23a8",
    path: "/handle/%E6%89%8B%E5%86%99call%E3%80%81apply%E3%80%81bind.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c9a23a8").then(next)
    },
  },
  {
    path: "/handle/手写call、apply、bind.html",
    redirect: "/handle/%E6%89%8B%E5%86%99call%E3%80%81apply%E3%80%81bind.html"
  },
  {
    path: "/handle/手写call、apply、bind.html",
    redirect: "/handle/%E6%89%8B%E5%86%99call%E3%80%81apply%E3%80%81bind.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-0b58b14a",
    path: "/tag/手写题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0b58b14a").then(next)
    },
    meta: {"pid":"tags","id":"手写题"}
  },
  {
    path: "/tag/手写题/index.html",
    redirect: "/tag/手写题/"
  },
  {
    name: "v-e8d86dc8",
    path: "/tag/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d86dc8").then(next)
    },
    meta: {"pid":"tags","id":"js"}
  },
  {
    path: "/tag/js/index.html",
    redirect: "/tag/js/"
  },
  {
    name: "v-32383f72",
    path: "/tag/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32383f72").then(next)
    },
    meta: {"pid":"tags","id":"git"}
  },
  {
    path: "/tag/git/index.html",
    redirect: "/tag/git/"
  },
  {
    name: "v-6b2c9986",
    path: "/categories/手写源码/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6b2c9986").then(next)
    },
    meta: {"pid":"categories","id":"手写源码"}
  },
  {
    path: "/categories/手写源码/index.html",
    redirect: "/categories/手写源码/"
  },
  {
    name: "v-41e61d1f",
    path: "/categories/frontEnd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-41e61d1f").then(next)
    },
    meta: {"pid":"categories","id":"frontEnd"}
  },
  {
    path: "/categories/frontEnd/index.html",
    redirect: "/categories/frontEnd/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]