/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Lee的博客",
  "description": "Lee",
  "base": "/blogs/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "heroText": "后汉书",
        "tagline": "人生在勤，不索何获。",
        "home": true,
        "heroImageStyle": {
          "maxWidth": "600px",
          "width": "100%",
          "display": "block",
          "margin": "9rem auto 2rem",
          "background": "#fff",
          "borderRadius": "1rem"
        },
        "bgImage": "f.jpg",
        "bgImageStyle": {
          "height": "1000px"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3851a994",
      "path": "/"
    },
    {
      "title": "1.md 测试",
      "frontmatter": {},
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-0384a2da",
      "path": "/blogs/1.html",
      "headers": [
        {
          "level": 2,
          "title": "1.md 测试",
          "slug": "_1-md-测试"
        }
      ]
    },
    {
      "title": "手写Promise源码",
      "frontmatter": {
        "title": "手写Promise源码",
        "date": "2020-06-21T00:00:00.000Z",
        "categories": [
          "手写源码"
        ],
        "tags": [
          "手写题"
        ]
      },
      "regularPath": "/handle/%E6%89%8B%E5%86%99Promise.html",
      "relativePath": "handle/手写Promise.md",
      "key": "v-499d3784",
      "path": "/handle/%E6%89%8B%E5%86%99Promise.html",
      "headers": [
        {
          "level": 3,
          "title": "完整源码如下：",
          "slug": "完整源码如下"
        }
      ]
    },
    {
      "title": "this关键字总结",
      "frontmatter": {
        "title": "this关键字总结",
        "date": "2020-12-10T00:00:00.000Z",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "js"
        ]
      },
      "regularPath": "/blogs/this%E5%85%B3%E9%94%AE%E5%AD%97%E6%80%BB%E7%BB%93.html",
      "relativePath": "blogs/this关键字总结.md",
      "key": "v-540052e4",
      "path": "/blogs/this%E5%85%B3%E9%94%AE%E5%AD%97%E6%80%BB%E7%BB%93.html",
      "headers": [
        {
          "level": 3,
          "title": "一、this 关键字调用方式",
          "slug": "一、this-关键字调用方式"
        }
      ]
    },
    {
      "title": "git常用操作指令",
      "frontmatter": {
        "title": "git常用操作指令",
        "date": "2019-09-28T00:00:00.000Z",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "git"
        ]
      },
      "regularPath": "/blogs/git%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html",
      "relativePath": "blogs/git常用指令.md",
      "key": "v-395e7a4c",
      "path": "/blogs/git%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html",
      "headers": [
        {
          "level": 3,
          "title": "1、git config",
          "slug": "_1、git-config"
        },
        {
          "level": 3,
          "title": "2、git 生成密钥",
          "slug": "_2、git-生成密钥"
        },
        {
          "level": 3,
          "title": "3、git remote",
          "slug": "_3、git-remote"
        },
        {
          "level": 3,
          "title": "4、git clone",
          "slug": "_4、git-clone"
        },
        {
          "level": 3,
          "title": "5、git branch",
          "slug": "_5、git-branch"
        },
        {
          "level": 3,
          "title": "6、git checkout",
          "slug": "_6、git-checkout"
        },
        {
          "level": 3,
          "title": "7、 git status 查看工作区和暂存区的状态",
          "slug": "_7、-git-status-查看工作区和暂存区的状态"
        },
        {
          "level": 3,
          "title": "8、git add 将工作区的修改添加到暂存区",
          "slug": "_8、git-add-将工作区的修改添加到暂存区"
        },
        {
          "level": 3,
          "title": "9、git commit",
          "slug": "_9、git-commit"
        },
        {
          "level": 3,
          "title": "10、git pull/push 拉取/提交",
          "slug": "_10、git-pull-push-拉取-提交"
        },
        {
          "level": 3,
          "title": "11、git merge 分支合并",
          "slug": "_11、git-merge-分支合并"
        },
        {
          "level": 3,
          "title": "12、git stash 本地存储",
          "slug": "_12、git-stash-本地存储"
        },
        {
          "level": 3,
          "title": "13、git log 日志过滤",
          "slug": "_13、git-log-日志过滤"
        },
        {
          "level": 3,
          "title": "14、git revert 代码撤销",
          "slug": "_14、git-revert-代码撤销"
        },
        {
          "level": 3,
          "title": "15、git reset 代码回滚",
          "slug": "_15、git-reset-代码回滚"
        },
        {
          "level": 3,
          "title": "16、git tag 版本号管理",
          "slug": "_16、git-tag-版本号管理"
        }
      ]
    },
    {
      "title": "手写call、apply、bind",
      "frontmatter": {
        "title": "手写call、apply、bind",
        "date": "2020-06-25T00:00:00.000Z",
        "categories": [
          "手写源码"
        ],
        "tags": [
          "手写题"
        ]
      },
      "regularPath": "/handle/%E6%89%8B%E5%86%99call%E3%80%81apply%E3%80%81bind.html",
      "relativePath": "handle/手写call、apply、bind.md",
      "key": "v-3c9a23a8",
      "path": "/handle/%E6%89%8B%E5%86%99call%E3%80%81apply%E3%80%81bind.html",
      "headers": [
        {
          "level": 3,
          "title": "1、手写call",
          "slug": "_1、手写call"
        },
        {
          "level": 3,
          "title": "2、手写apply",
          "slug": "_2、手写apply"
        },
        {
          "level": 3,
          "title": "3、手写bind",
          "slug": "_3、手写bind"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "手写题 Tags"
      },
      "regularPath": "/tag/%E6%89%8B%E5%86%99%E9%A2%98/",
      "key": "v-0b58b14a",
      "path": "/tag/手写题/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js Tags"
      },
      "regularPath": "/tag/js/",
      "key": "v-e8d86dc8",
      "path": "/tag/js/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "git Tags"
      },
      "regularPath": "/tag/git/",
      "key": "v-32383f72",
      "path": "/tag/git/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "手写源码 Categories"
      },
      "regularPath": "/categories/%E6%89%8B%E5%86%99%E6%BA%90%E7%A0%81/",
      "key": "v-6b2c9986",
      "path": "/categories/手写源码/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "frontEnd Categories"
      },
      "regularPath": "/categories/frontEnd/",
      "key": "v-41e61d1f",
      "path": "/categories/frontEnd/"
    }
  ],
  "themeConfig": {
    "author": "Lee",
    "logo": "/avatar.png",
    "authorAvatar": "/avatar.png",
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "head": [
      [
        "meta",
        {
          "name": "viewport",
          "content": "width=device-width,initial-scale=1,user-scalable=no"
        }
      ]
    ],
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "我的",
        "icon": "reco-account",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/3755587450438797"
          },
          {
            "text": "Github",
            "link": "https://github.com/lgq820"
          }
        ]
      },
      {
        "text": "TimeLine",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}