/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Lee的博客",
  "description": "Lee",
  "base": "/blogs/",
  "headTags": [],
  "pages": [
    {
      "title": "1.md 测试",
      "frontmatter": {},
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-0384a2da",
      "path": "/blogs/1.html",
      "headers": [
        {
          "level": 2,
          "title": "1.md 测试",
          "slug": "_1-md-测试"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "heroText": "后汉书",
        "tagline": "人生在勤，不索何获。",
        "home": true,
        "heroImageStyle": {
          "maxWidth": "600px",
          "width": "100%",
          "display": "block",
          "margin": "9rem auto 2rem",
          "background": "#fff",
          "borderRadius": "1rem"
        },
        "bgImage": "f.jpg",
        "bgImageStyle": {
          "height": "1000px"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3851a994",
      "path": "/"
    },
    {
      "title": "这是第二个文件",
      "frontmatter": {},
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-55e3597a",
      "path": "/blogs/2.html",
      "headers": [
        {
          "level": 2,
          "title": "这是第二个文件",
          "slug": "这是第二个文件"
        }
      ]
    },
    {
      "title": "前端面试题",
      "frontmatter": {},
      "regularPath": "/%E5%89%8D%E7%AB%AF/%E5%89%8D%E7%AB%AF%E9%9D%A2%E8%AF%95.html",
      "relativePath": "前端/前端面试.md",
      "key": "v-4093ff12",
      "path": "/%E5%89%8D%E7%AB%AF/%E5%89%8D%E7%AB%AF%E9%9D%A2%E8%AF%95.html",
      "headers": [
        {
          "level": 3,
          "title": "前端面试题",
          "slug": "前端面试题"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "author": "Lee",
    "logo": "/avatar.png",
    "authorAvatar": "/avatar.png",
    "type": "blog",
    "head": [
      [
        "meta",
        {
          "name": "viewport",
          "content": "width=device-width,initial-scale=1,user-scalable=no"
        }
      ]
    ],
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "我的",
        "icon": "reco-account",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/3755587450438797"
          },
          {
            "text": "Github",
            "link": "https://github.com/lgq820"
          }
        ]
      },
      {
        "text": "TimeLine",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}