/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "手写题": {
      "key": "手写题",
      "scope": "tags",
      "path": "/tag/手写题/",
      "pageKeys": [
        "v-499d3784",
        "v-3c9a23a8"
      ]
    },
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tag/js/",
      "pageKeys": [
        "v-540052e4"
      ]
    },
    "git": {
      "key": "git",
      "scope": "tags",
      "path": "/tag/git/",
      "pageKeys": [
        "v-395e7a4c"
      ]
    }
  },
  "categories": {
    "手写源码": {
      "key": "手写源码",
      "scope": "categories",
      "path": "/categories/手写源码/",
      "pageKeys": [
        "v-499d3784",
        "v-3c9a23a8"
      ]
    },
    "frontEnd": {
      "key": "frontEnd",
      "scope": "categories",
      "path": "/categories/frontEnd/",
      "pageKeys": [
        "v-540052e4",
        "v-395e7a4c"
      ]
    }
  },
  "timeline": {}
}