/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "手写题",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/手写题/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "js",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/js/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "git",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/git/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "手写源码",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/手写源码/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "frontEnd",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/frontEnd/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
}]